apiVersion: v1
kind: ServiceAccount
metadata:
  name: grpcbin-hello-world
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "hello-world.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcbin-{{ include "hello-world.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "hello-world.selectorLabels" . | nindent 6 }}
      app: grpcbin
  template:
    metadata:
      labels:
        {{- include "hello-world.selectorLabels" . | nindent 8 }}
        app: grpcbin
    spec:
      serviceAccountName: grpcbin-hello-world
      containers:
        - name: grpcbin
          image: "moul/grpcbin:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 9001
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: grpcbin-{{ include "hello-world.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "hello-world.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grpcbin-{{ include "hello-world.fullname" . }}
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: grpcbin-{{ include "hello-world.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "hello-world.labels" . | nindent 4 }}
spec:
  ports:
    - port: 50051
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "hello-world.selectorLabels" . | nindent 4 }}
    app: grpcbin
