apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "hello-world.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - {{ .Values.domain }}
    - {{ include "hello-world.fullname" . }}
  gateways:
    - istio-system/main-gateway
    - mesh
  http:
    - match:
      - port: 80
      - port: 443
      route:
        - destination:
            host:  {{ include "hello-world.fullname" . }}.{{ .Values.namespace }}.svc.cluster.local
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ include "hello-world.fullname" . }}
  namespace: istio-system
spec:
  addresses:
    - 10.1.1.1
  hosts:
    - "{{ include "hello-world.fullname" . }}.internal"
  ports:
    - name: http
      number: 80
      protocol: HTTP