apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "k8s-service.namespaceName" . }}
  name: secret
type: Opaque
data:
  {{- range $val := .Values.secrets }}
  {{ $val }}: "Cg=="
  {{ end -}}
