apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "k8s-service.namespaceName" . }}
  name: secret
type: Opaque
data:
  {{- $existing := (lookup "v1" "Secret" ( include "k8s-service.namespaceName" . ) "secret").data -}}
  {{- range $val := .Values.secrets }}
  {{ $val }}: {{ (default "Cg==" (get $existing $val)) }}
  {{ end -}}
