apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-service.fullname" . }}
  labels:
    {{- include "k8s-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ include "k8s-service.namespaceName" . }}
