apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-service.fullname" . }}
  labels:
    {{- include "k8s-service.labels" . | nindent 4 }}
  namespace: {{ .Release.Name }}
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "k8s-service.selectorLabels" . | nindent 4 }}
