apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "k8s-service.fullname" . }}
  namespace: {{ .Release.Name }}
spec:
  hosts:
    {{- if .Values.domain }}
    - "{{ .Values.domain }}"
    {{- end }}
    - "{{ include "k8s-service.fullname" . }}"
    - "{{ include "k8s-service.fullname" . }}.internal"
  gateways:
    {{- if .Values.domain }}
    - istio-system/main-gateway
    {{- end }}
    - mesh
  http:
    - match:
      - port: 80
        gateways:
        - mesh
      {{- if .Values.domain }}
      - port: 443
        gateways:
        - istio-system/main-gateway
        {{- if .Values.uriPrefix }}
        ignoreUriCase: true
        uri:
          prefix: {{ .Values.uriPrefix }}
        {{- end }}
      {{- end }}
      route:
        - destination:
            host:  {{ include "k8s-service.fullname" . }}.{{ .Release.Name }}.svc.cluster.local
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ include "k8s-service.fullname" . }}
  namespace: istio-system
spec:
  addresses:
    - 8.8.8.8
  hosts:
    - "{{ include "k8s-service.fullname" . }}.internal"
  ports:
    - name: http
      number: 80
      protocol: HTTP